// GMAT Quant 概念词库 —— 英文概念 → 中文映射
// cat: number（数论与算术）| algebra（代数）| geometry（几何）| stats（统计与集合）| prob（概率与组合）| word（文字题表达）
// en: 英文概念 | cn: 中文概念 | hint: 一句话本质/速记 | example: GMAT 风格题目例句

const WORDS = [
  // ===================== number 数论与算术 =====================
  { en: "integer", cn: "整数", hint: "⋯, −2, −1, 0, 1, 2⋯；GMAT 说 integer 就排除分数小数", example: "If n is an integer, which of the following must be an integer?", cat: "number" },
  { en: "even", cn: "偶数", hint: "能被 2 整除，个位是 0/2/4/6/8；唯一偶质数是 2", example: "If n is even, which of the following must be even?", cat: "number" },
  { en: "odd", cn: "奇数", hint: "不能被 2 整除；奇数×奇数=奇数，奇数+偶数=奇数", example: "The product of two consecutive odd integers is 143.", cat: "number" },
  { en: "consecutive integers", cn: "连续整数", hint: "差 1 的整数串 n, n+1, n+2⋯；连续偶数/奇数差 2，设为 x, x+2, x+4", example: "The sum of three consecutive integers is 51. What is the middle integer?", cat: "number" },
  { en: "prime number", cn: "质数", hint: "只有 1 和自己两个因数；2 是唯一偶质数；最小质数是 2", example: "How many prime numbers are between 10 and 20?", cat: "number" },
  { en: "composite", cn: "合数", hint: "除 1 和自身外还有其他因数；4 是最小合数", example: "Which of the following is a composite number? (A) 13 (B) 17 (C) 21", cat: "number" },
  { en: "factor", cn: "因数（约数）", hint: "能整除该数的数；找因数成对出现，从小往大试", example: "How many positive factors does 36 have?", cat: "number" },
  { en: "multiple", cn: "倍数", hint: "该数乘以整数得到；24 是 6 的倍数", example: "Which of the following is a multiple of both 4 and 6?", cat: "number" },
  { en: "divisible by", cn: "可被……整除", hint: "除以该数余数为 0；24 is divisible by 8", example: "If n is divisible by both 3 and 5, n must be divisible by which of the following?", cat: "number" },
  { en: "remainder", cn: "余数", hint: "被除数 = 除数×商 + 余数；余数一定小于除数", example: "When n is divided by 7, the remainder is 3. What is the remainder when n + 4 is divided by 7?", cat: "number" },
  { en: "quotient", cn: "商", hint: "除法结果；20 ÷ 5 的商是 4", example: "The quotient of x and 3 is 12. What is x?", cat: "number" },
  { en: "greatest common divisor", cn: "最大公约数（GCD）", hint: "公共因数里最大的；质因数分解后取交集", example: "What is the greatest common divisor of 36 and 60?", cat: "number" },
  { en: "least common multiple", cn: "最小公倍数（LCM）", hint: "公共倍数里最小的；周期重合问题用 LCM", example: "Two machines beep every 12 and 18 minutes. If they beep together now, after how many minutes will they next beep together?", cat: "number" },
  { en: "units digit", cn: "个位数", hint: "最右边一位；个位数循环规律题从 1 次方开始找周期", example: "What is the units digit of 7¹⁰¹?", cat: "number" },
  { en: "fraction", cn: "分数", hint: "分子/分母；真分数 <1，假分数 ≥1", example: "Which of the following fractions is closest to 1/2?", cat: "number" },
  { en: "numerator", cn: "分子", hint: "分数线上面的数", example: "If the numerator of a fraction is increased by 20% and the denominator is unchanged, the fraction increases by what percent?", cat: "number" },
  { en: "denominator", cn: "分母", hint: "分数线下面的数；分母不能为 0", example: "Which of the following values of x makes the denominator equal to zero?", cat: "number" },
  { en: "reciprocal", cn: "倒数", hint: "分子分母互换；乘积为 1；0 没有倒数", example: "The reciprocal of a number is 2/3. What is the number?", cat: "number" },
  { en: "terminating decimal", cn: "有限小数", hint: "能除尽；分母质因数只有 2 和 5 时才是有限小数", example: "Which of the following fractions is a terminating decimal? (A) 1/3 (B) 1/6 (C) 1/8", cat: "number" },
  { en: "rounding", cn: "四舍五入", hint: "看保留位后一位，≥5 进一，<5 舍去", example: "What is 3.476 rounded to the nearest hundredth?", cat: "number" },
  { en: "absolute value", cn: "绝对值", hint: "到 0 的距离，永远 ≥0；|x| = 3 则 x = ±3", example: "If |x − 3| = 5, what are the possible values of x?", cat: "number" },
  { en: "perfect square", cn: "完全平方数", hint: "某个整数的平方；1, 4, 9, 16⋯；因数个数是奇数", example: "Which of the following is a perfect square? (A) 32 (B) 48 (C) 64", cat: "number" },
  { en: "square root", cn: "平方根", hint: "哪个数平方等于它；√25 = 5（只取非负）", example: "What is the value of √144?", cat: "number" },
  { en: "exponent", cn: "指数（幂）", hint: "aⁿ 中 n 是指数；同底数相乘指数相加", example: "What is the value of 2³ × 2⁴?", cat: "number" },
  { en: "base", cn: "底数", hint: "aⁿ 中 a 是底数", example: "In the expression 5³, the base is 5 and the exponent is 3.", cat: "number" },
  { en: "sequence", cn: "数列", hint: "按规律排的一串数；找规律看相邻项的差或比", example: "The first term of a sequence is 3, and each term after the first is 2 more than the previous term. What is the 10th term?", cat: "number" },
  { en: "arithmetic sequence", cn: "等差数列", hint: "相邻项差为定值 d；aₙ = a₁ + (n−1)d", example: "In an arithmetic sequence, the first term is 5 and the common difference is 3. What is the 8th term?", cat: "number" },
  { en: "geometric sequence", cn: "等比数列", hint: "相邻项比为定值 r；aₙ = a₁·rⁿ⁻¹", example: "In a geometric sequence, the first term is 2 and each term is 3 times the previous term. What is the 4th term?", cat: "number" },

  // ===================== algebra 代数 =====================
  { en: "variable", cn: "变量", hint: "用字母表示未知数，x, y, n⋯", example: "If 3x + 5 = 20, what is the value of x?", cat: "algebra" },
  { en: "coefficient", cn: "系数", hint: "字母前面的数字倍数；3x 的系数是 3", example: "In the expression 4x² + 7x − 2, what is the coefficient of x?", cat: "algebra" },
  { en: "equation", cn: "方程", hint: "带等号的式子；解方程=求出未知数", example: "Solve the equation 2x − 7 = 13.", cat: "algebra" },
  { en: "quadratic equation", cn: "二次方程", hint: "ax² + bx + c = 0；求根公式或十字相乘", example: "What are the solutions to x² − 5x + 6 = 0?", cat: "algebra" },
  { en: "inequality", cn: "不等式", hint: ">、<、≥、≤；两边同乘负数要变号", example: "If 2x − 3 > 7, which of the following must be true?", cat: "algebra" },
  { en: "solution", cn: "解（根）", hint: "代入使等式成立的数", example: "Which of the following is a solution to the equation x² = 9?", cat: "algebra" },
  { en: "function", cn: "函数", hint: "每个 x 对应唯一 y；f(x) 把 x 换成括号里的数", example: "If f(x) = 2x + 1, what is f(3)?", cat: "algebra" },
  { en: "domain", cn: "定义域", hint: "x 允许取的范围；分母≠0、根号内≥0", example: "What is the domain of f(x) = 1/(x − 2)?", cat: "algebra" },
  { en: "slope", cn: "斜率", hint: "直线的倾斜程度，(y₂−y₁)/(x₂−x₁)；y = mx + b 里的 m", example: "What is the slope of the line passing through (1, 2) and (3, 8)?", cat: "algebra" },
  { en: "intercept", cn: "截距", hint: "与轴的交点；x-intercept 令 y=0，y-intercept 令 x=0", example: "What is the y-intercept of the line y = 3x − 6?", cat: "algebra" },
  { en: "coordinate plane", cn: "坐标平面", hint: "x 轴 y 轴构成的平面，点记作 (x, y)", example: "In which quadrant does the point (−3, 4) lie?", cat: "algebra" },
  { en: "origin", cn: "原点", hint: "(0, 0)，两轴交点", example: "What is the distance from the point (3, 4) to the origin?", cat: "algebra" },
  { en: "quadrant", cn: "象限", hint: "四块区域：I (+,+) II (−,+) III (−,−) IV (+,−)", example: "In which quadrant is the point (−2, −5)?", cat: "algebra" },
  { en: "perpendicular", cn: "垂直", hint: "成 90°；两直线斜率乘积 = −1", example: "Line m is perpendicular to line n. If the slope of m is 2, what is the slope of n?", cat: "algebra" },
  { en: "parallel", cn: "平行", hint: "永不相交；两直线斜率相等", example: "Line k is parallel to the line y = 3x + 2. What is the slope of line k?", cat: "algebra" },
  { en: "in terms of", cn: "用……表示", hint: "把结果写成含指定字母的式子", example: "If 2x + y = 10, express y in terms of x.", cat: "algebra" },
  { en: "distinct", cn: "互不相同的", hint: "各不一样，不允许重复取值", example: "How many distinct prime factors does 84 have?", cat: "algebra" },
  { en: "satisfies the equation", cn: "满足方程", hint: "代入后等式成立；判断选项直接代", example: "Which of the following values of x satisfies the equation x² − 4 = 0?", cat: "algebra" },
  { en: "solve for", cn: "解出（某量）", hint: "把要求的未知数单独放等号一边", example: "Solve for y in the equation 2y + 3x = 12.", cat: "algebra" },
  { en: "expression", cn: "表达式", hint: "没有等号的式子，只能化简不能解", example: "Simplify the expression 3(x + 2) − 2x.", cat: "algebra" },
  { en: "factor (verb)", cn: "因式分解", hint: "把式子写成乘积形式；x²−5x+6 = (x−2)(x−3)", example: "Factor x² − 9 completely.", cat: "algebra" },

  // ===================== geometry 几何 =====================
  { en: "isosceles triangle", cn: "等腰三角形", hint: "两条边相等，两个底角相等", example: "In an isosceles triangle, one angle is 40°. What is the measure of one of the other angles?", cat: "geometry" },
  { en: "equilateral triangle", cn: "等边三角形", hint: "三边相等、三角都是 60°", example: "Each side of an equilateral triangle has length 6. What is its perimeter?", cat: "geometry" },
  { en: "right triangle", cn: "直角三角形", hint: "有一个 90° 角；勾股定理用武之地", example: "In right triangle ABC, the legs have lengths 5 and 12. What is the length of the hypotenuse?", cat: "geometry" },
  { en: "hypotenuse", cn: "斜边", hint: "直角三角形最长边，正对直角", example: "The legs of a right triangle are 6 and 8. What is the hypotenuse?", cat: "geometry" },
  { en: "Pythagorean theorem", cn: "勾股定理", hint: "a² + b² = c²；3-4-5、5-12-13 常考", example: "In a right triangle, the legs are 3 and 4. What is the hypotenuse?", cat: "geometry" },
  { en: "acute angle", cn: "锐角", hint: "小于 90° 的角", example: "Two angles of a triangle are 50° and 60°. What is the measure of the third angle?", cat: "geometry" },
  { en: "obtuse angle", cn: "钝角", hint: "大于 90° 小于 180° 的角", example: "Can a triangle have one right angle and one obtuse angle?", cat: "geometry" },
  { en: "vertex", cn: "顶点", hint: "两条边相交的点；三角形 3 个顶点", example: "A square has four vertices. How many vertices does a cube have?", cat: "geometry" },
  { en: "quadrilateral", cn: "四边形", hint: "四条边的多边形；内角和 360°", example: "Three angles of a quadrilateral measure 90°, 100°, and 80°. What is the fourth angle?", cat: "geometry" },
  { en: "parallelogram", cn: "平行四边形", hint: "两组对边平行；对边相等、对角相等", example: "In a parallelogram, one angle is 70°. What is the measure of an adjacent angle?", cat: "geometry" },
  { en: "rhombus", cn: "菱形", hint: "四边相等的平行四边形；对角线互相垂直", example: "A rhombus has a side of length 5. What is its perimeter?", cat: "geometry" },
  { en: "trapezoid", cn: "梯形", hint: "只有一组对边平行；面积=(上底+下底)×高÷2", example: "The bases of a trapezoid are 4 and 10, and its height is 5. What is its area?", cat: "geometry" },
  { en: "radius", cn: "半径", hint: "圆心到圆周的距离；直径的一半", example: "If the area of a circle is 36π, what is its radius?", cat: "geometry" },
  { en: "diameter", cn: "直径", hint: "穿过圆心的弦；等于两倍半径", example: "If the circumference of a circle is 12π, what is its diameter?", cat: "geometry" },
  { en: "circumference", cn: "圆周长", hint: "C = 2πr = πd", example: "What is the circumference of a circle with radius 6?", cat: "geometry" },
  { en: "arc", cn: "弧", hint: "圆周的一段；弧长 ∝ 圆心角/360°", example: "In a circle, a central angle of 60° intercepts an arc. What fraction of the circumference is the arc?", cat: "geometry" },
  { en: "sector", cn: "扇形", hint: "两条半径+一段弧围成的「披萨块」；面积=圆面积×角度占比", example: "A sector of a circle has a central angle of 90°. What fraction of the circle's area is the sector?", cat: "geometry" },
  { en: "chord", cn: "弦", hint: "圆上任意两点连线；直径是最长弦", example: "In a circle with radius 5, what is the length of the longest chord?", cat: "geometry" },
  { en: "tangent", cn: "切线", hint: "与圆只有一个交点；垂直于过切点的半径", example: "A line is tangent to a circle at point P. What angle does it form with the radius drawn to P?", cat: "geometry" },
  { en: "inscribed", cn: "内接的", hint: "图形在圆内部、顶点都在圆上；内接角=对弧一半", example: "A square is inscribed in a circle. If the circle's radius is 5, what is the square's area?", cat: "geometry" },
  { en: "congruent", cn: "全等", hint: "形状大小完全相同；对应边角全相等", example: "Triangles ABC and DEF are congruent. If AB = 7, what is the length of the corresponding side of DEF?", cat: "geometry" },
  { en: "similar", cn: "相似", hint: "形状相同大小不同；对应角相等、对应边成比例", example: "Triangles P and Q are similar. If their corresponding sides are in the ratio 2:3, what is the ratio of their areas?", cat: "geometry" },
  { en: "area", cn: "面积", hint: "图形内部大小；单位是平方", example: "What is the area of a rectangle with length 8 and width 5?", cat: "geometry" },
  { en: "perimeter", cn: "周长", hint: "所有边长之和；单位不是平方", example: "What is the perimeter of a rectangle with length 8 and width 5?", cat: "geometry" },
  { en: "volume", cn: "体积", hint: "立体图形所占空间；长×宽×高", example: "What is the volume of a cube with edge length 4?", cat: "geometry" },
  { en: "surface area", cn: "表面积", hint: "立体所有面的面积总和", example: "What is the surface area of a cube with edge length 4?", cat: "geometry" },
  { en: "diagonal", cn: "对角线", hint: "不相邻顶点连线；矩形对角线=√(a²+b²)", example: "What is the length of the diagonal of a rectangle with sides 3 and 4?", cat: "geometry" },
  { en: "midpoint", cn: "中点", hint: "线段正中间的点；坐标取两端平均值", example: "What is the midpoint of the segment joining (2, 4) and (6, 10)?", cat: "geometry" },
  { en: "bisect", cn: "平分", hint: "分成相等的两份", example: "Line l bisects angle A, which measures 80°. What is the measure of each resulting angle?", cat: "geometry" },

  // ===================== stats 统计与集合 =====================
  { en: "arithmetic mean", cn: "算术平均数", hint: "总和÷个数；「average」默认就是它", example: "The average of 5, 8, and x is 7. What is x?", cat: "stats" },
  { en: "weighted average", cn: "加权平均数", hint: "各部分按权重贡献；总=各组(均值×个数)之和", example: "A class of 20 students averaged 70, and a class of 30 students averaged 80. What is the combined average?", cat: "stats" },
  { en: "median", cn: "中位数", hint: "排序后正中间的数；偶数个取中间两个的平均", example: "What is the median of {3, 1, 7, 5, 9}?", cat: "stats" },
  { en: "mode", cn: "众数", hint: "出现次数最多的数；可能有多个或没有", example: "What is the mode of {2, 3, 3, 5, 5, 5, 7}?", cat: "stats" },
  { en: "range", cn: "极差", hint: "最大值−最小值", example: "What is the range of {12, 7, 19, 4, 10}?", cat: "stats" },
  { en: "standard deviation", cn: "标准差", hint: "数据离平均值的平均离散程度；越集中越小", example: "Which set has the smallest standard deviation? (A) {1, 50, 99} (B) {48, 50, 52}", cat: "stats" },
  { en: "set", cn: "集合", hint: "一组元素，不重复不排序", example: "How many elements are in the set {2, 4, 6, 8}?", cat: "stats" },
  { en: "element", cn: "元素", hint: "集合里的成员", example: "How many elements does the set {1, 2, 3, 4} have?", cat: "stats" },
  { en: "subset", cn: "子集", hint: "取集合的一部分（含全取和不取）", example: "How many subsets does the set {a, b, c} have?", cat: "stats" },
  { en: "union", cn: "并集", hint: "两个集合的所有元素合起来；「或」的关系", example: "If A = {1, 2, 3} and B = {3, 4, 5}, what is A ∪ B?", cat: "stats" },
  { en: "intersection", cn: "交集", hint: "两个集合共有的元素；「且」的关系", example: "If A = {1, 2, 3} and B = {3, 4, 5}, what is A ∩ B?", cat: "stats" },
  { en: "mutually exclusive", cn: "互斥", hint: "不可能同时发生；P(A 或 B) = P(A)+P(B)", example: "Rolling a 2 and rolling an odd number on a die are mutually exclusive events.", cat: "stats" },
  { en: "frequency", cn: "频数", hint: "某值出现的次数；分布表里那一栏", example: "In the data set {2, 2, 2, 5, 5, 8}, what is the frequency of 5?", cat: "stats" },

  // ===================== prob 概率与组合 =====================
  { en: "probability", cn: "概率", hint: "有利结果数÷总结果数；0 到 1 之间", example: "A bag contains 3 red and 2 blue marbles. What is the probability of drawing a red marble?", cat: "prob" },
  { en: "event", cn: "事件", hint: "关注的某种结果；「抽到红球」是一个事件", example: "In rolling a die, the event of rolling an even number has how many outcomes?", cat: "prob" },
  { en: "at random", cn: "随机地", hint: "每个结果等可能", example: "Two numbers are chosen at random from {1, 2, 3, 4, 5}. How many pairs are possible?", cat: "prob" },
  { en: "permutation", cn: "排列", hint: "顺序重要；n 个取 r 个排队 P(n,r) = n!/(n−r)!", example: "In how many ways can 3 books be arranged on a shelf if 5 books are available?", cat: "prob" },
  { en: "combination", cn: "组合", hint: "顺序不重要，只关心选谁；C(n,r) = n!/(r!(n−r)!)", example: "In how many ways can a committee of 2 be chosen from 5 people?", cat: "prob" },
  { en: "factorial", cn: "阶乘", hint: "n! = n×(n−1)×⋯×1；0! = 1", example: "What is the value of 5! / 3!?", cat: "prob" },
  { en: "with replacement", cn: "放回抽样", hint: "抽完放回去，每次概率不变", example: "A card is drawn from a deck and replaced. What is the probability of drawing a heart twice in a row?", cat: "prob" },
  { en: "without replacement", cn: "不放回抽样", hint: "抽完不放回，总数递减，概率逐次变化", example: "Two marbles are drawn without replacement from a bag of 3 red and 2 blue. What is the probability both are red?", cat: "prob" },
  { en: "independent events", cn: "独立事件", hint: "互不影响；P(A 且 B) = P(A)×P(B)", example: "The probability of event A is 1/2 and of independent event B is 1/3. What is the probability both occur?", cat: "prob" },

  // ===================== word 文字题表达 =====================
  { en: "sum", cn: "和", hint: "加法结果；「sum of」后接所有加数", example: "The sum of x and twice y is 15. Write the equation.", cat: "word" },
  { en: "difference", cn: "差", hint: "减法结果；大减小", example: "The difference between two numbers is 8. If the larger is 20, what is the smaller?", cat: "word" },
  { en: "product", cn: "积", hint: "乘法结果", example: "The product of two consecutive integers is 42. What are the integers?", cat: "word" },
  { en: "twice as many as", cn: "是……的两倍", hint: "A is twice as many as B → A = 2B；先找准基准量", example: "There are twice as many boys as girls. If there are 36 students in total, how many are girls?", cat: "word" },
  { en: "at least", cn: "至少", hint: "≥；至少一个=1−一个都没有", example: "If n is at least 5, which inequality represents this? (A) n > 5 (B) n ≥ 5", cat: "word" },
  { en: "at most", cn: "至多", hint: "≤", example: "A car travels at most 60 miles per hour. If it drives for 3 hours, what is the maximum distance?", cat: "word" },
  { en: "percent increase", cn: "百分比增加", hint: "增加量÷原值；原值×(1+p%)", example: "The price of a stock increased from $40 to $52. By what percent did it increase?", cat: "word" },
  { en: "percent decrease", cn: "百分比减少", hint: "减少量÷原值；原值×(1−p%)", example: "A jacket's price decreased from $80 to $60. By what percent did it decrease?", cat: "word" },
  { en: "discount", cn: "折扣", hint: "原价×折扣率=减去的钱；off 20% 指减 20%", example: "A shirt is on sale at 20% off the regular price of $50. What is the sale price?", cat: "word" },
  { en: "markup", cn: "加价", hint: "成本×(1+加价率)=售价", example: "A store marks up an item that costs $30 by 40%. What is the selling price?", cat: "word" },
  { en: "profit", cn: "利润", hint: "收入−成本；profit = revenue − cost", example: "A merchant buys an item for $60 and sells it for $90. What is the profit?", cat: "word" },
  { en: "revenue", cn: "收入", hint: "单价×销量", example: "A store sells 200 units at $15 each. What is its revenue?", cat: "word" },
  { en: "simple interest", cn: "单利", hint: "只对本金计息；I = P×r×t", example: "At 5% simple annual interest, how much interest does $2,000 earn in 3 years?", cat: "word" },
  { en: "compound interest", cn: "复利", hint: "利滚利；A = P(1+r)ⁿ", example: "A bank account pays 10% interest compounded annually. What is $1,000 worth after 2 years?", cat: "word" },
  { en: "principal", cn: "本金", hint: "最初投入/借出的钱", example: "If the simple interest on a principal of $5,000 is $750 over 3 years, what is the annual rate?", cat: "word" },
  { en: "average speed", cn: "平均速度", hint: "总路程÷总时间；不是两个速度的平均！", example: "A car travels 60 miles at 40 mph and another 60 miles at 60 mph. What is its average speed for the whole trip?", cat: "word" },
  { en: "rate", cn: "速率", hint: "单位时间做的量；距离=速度×时间", example: "A printer prints at a rate of 12 pages per minute. How many pages in 15 minutes?", cat: "word" },
  { en: "ratio", cn: "比", hint: "A:B = A÷B；比相加得总份数", example: "The ratio of boys to girls is 3:4. If there are 28 girls, how many boys are there?", cat: "word" },
  { en: "proportion", cn: "比例（式）", hint: "两个比相等；交叉相乘", example: "If 3 apples cost $2, how much do 12 apples cost at the same rate?", cat: "word" },
  { en: "mixture", cn: "混合", hint: "浓度/成分混合：总量守恒列方程", example: "How many liters of a 20% salt solution must be added to 10 liters of a 50% solution to make a 30% solution?", cat: "word" },
  { en: "inclusive", cn: "含端点", hint: "「1 to 5, inclusive」= 1, 2, 3, 4, 5；个数=大−小+1", example: "How many integers from 5 to 15, inclusive, are there?", cat: "word" },
  { en: "between", cn: "在……之间（不含端点）", hint: "GMAT 中 between 通常不含两端", example: "How many integers are between 5 and 10?", cat: "word" },
  { en: "greater than or equal to", cn: "大于等于", hint: "≥；「no less than」同义", example: "If x is greater than or equal to 4, which of the following could be x? (A) 3.9 (B) 4 (C) 4.1", cat: "word" },
  { en: "rounded to the nearest", cn: "四舍五入到", hint: "精确到某一位；看下一位决定进舍", example: "What is 47.368 rounded to the nearest tenth?", cat: "word" },
  { en: "combined rate", cn: "合并速率", hint: "一起干活的速率=各自速率之和；工程题倒数", example: "Machine A fills a tank in 4 hours and machine B in 6 hours. Working together, how long to fill the tank?", cat: "word" },
  { en: "sales tax", cn: "销售税", hint: "价格×税率；税后总价=价格×(1+税率)", example: "A $25 book is taxed at 8%. What is the total cost?", cat: "word" },
  { en: "commission", cn: "佣金", hint: "按销售额的百分比提取", example: "A salesperson earns a 15% commission on sales. If sales are $4,000, what is the commission?", cat: "word" },
  { en: "deposit", cn: "存款", hint: "存进账户的钱；本金类", example: "Jane deposits $1,500 into an account. Her balance is now $6,200. What was her previous balance?", cat: "word" },
  { en: "installment", cn: "分期付款", hint: "总价分多次付", example: "A $1,200 phone is paid in 6 equal installments. How much is each installment?", cat: "word" },
  { en: "per capita", cn: "人均", hint: "总量÷人数", example: "A country of 40 million people has a GDP of $800 billion. What is the per capita GDP?", cat: "word" },
];

// 专题中文名（index.html 引用）
const CATEGORIES = {
  number: "数论与算术",
  algebra: "代数",
  geometry: "几何",
  stats: "统计与集合",
  prob: "概率与组合",
  word: "文字题表达",
};
